name: Development Release

on:
  push:
    branches:
      - canary/*

jobs:
  release:
    runs-on: ubuntu-latest
    # FIXME: This is a temporary fix for deprecated commands
    # see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setting up environment
        uses: waifu-motivator/wmp-env-action@v1.0.0
        with:
          release-type: non-prod
      - run: ./ciScripts/buildPlugin.sh
      - run: ./gradlew publishPlugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
